#include "Generator.h"

/* MODULE INTERNAL STATE */

static Logger * _logger = NULL;
static SVGContext _svgContext;
static int _svgWidth = 800;
static int _svgHeight = 600;
static int _centerX = 400;
static int _centerY = 300;

void initializeGeneratorModule() {
	_logger = createLogger("Generator");
	// Initialize default SVG context
	_svgContext.fillColor = 0x000000; // Black
	_svgContext.strokeColor = 0x000000; // Black
	_svgContext.strokeWidth = 1;
	_svgContext.layer = 0; // Back layer by default
}

void shutdownGeneratorModule() {
	if (_logger != NULL) {
		destroyLogger(_logger);
	}
}

/** PRIVATE FUNCTIONS */

static void _generateSVGHeader(FILE* outputFile);
static void _generateSVGFooter(FILE* outputFile);
static void _generateProgram(FILE* outputFile, Program * program);
static void _generateSentences(FILE* outputFile, Sentences * sentences);
static void _generateSentence(FILE* outputFile, Sentence * sentence);
static void _generateExpression(Expression * expression);
static void _generateFactor(Factor * factor);
static void _generateFunctionCall(FILE* outputFile, char * functionName, ExpressionList * arguments);
static void _generateCircle(FILE* outputFile, ExpressionList * arguments);
static void _generateCurve(FILE* outputFile, ExpressionList * arguments);
static void _generateStroke(ExpressionList * arguments);
static void _generateFill(ExpressionList * arguments);
static void _generateLayer(ExpressionList * arguments);
static void _generateLog(FILE* outputFile, StringPartList * stringParts);
static void _generateImport(FILE* outputFile, StringPartList * importPath);
static float _evaluateExpressionAsFloat(Expression * expression);
static int _evaluateExpressionAsInt(Expression * expression);
static VectorData _evaluateExpressionAsVector(Expression * expression);
static void _generateStringOutput(FILE* outputFile, StringPartList * stringParts);
static char* _colorToHex(int color);

/**
 * Converts a color integer to hex string format
 */
static char* _colorToHex(int color) {
    char* hexColor = malloc(8);
    sprintf(hexColor, "#%06X", color & 0xFFFFFF);
    return hexColor;
}

/**
 * Generates the SVG header with basic structure
 */
static void _generateSVGHeader(FILE* outputFile) {
    fprintf(outputFile, "<svg width=\"%d\" height=\"%d\" xmlns=\"http://www.w3.org/2000/svg\">\n", _svgWidth, _svgHeight);
    fprintf(outputFile, "  <defs>\n");
    fprintf(outputFile, "    <style>\n");
    fprintf(outputFile, "      .back-layer { z-index: 0; }\n");
    fprintf(outputFile, "      .front-layer { z-index: 1; }\n");
    fprintf(outputFile, "    </style>\n");
    fprintf(outputFile, "  </defs>\n");
    fprintf(outputFile, "  <!-- Generated by Dibujitos Compiler -->\n");
}

/**
 * Generates the SVG footer
 */
static void _generateSVGFooter(FILE* outputFile) {
    fprintf(outputFile, "</svg>\n");
}

/**
 * Evaluates an expression and returns its float value
 */
static float _evaluateExpressionAsFloat(Expression * expression) {
    if (!expression) return 0.0f;
    
    switch (expression->type) {
        case FACTOR:
            switch (expression->factor->type) {
                case INTEGER_FACTOR:
                    return (float)expression->factor->integerExpression;
                case DECIMAL_FACTOR:
                    return expression->factor->floatExpression;
                case IDENTIFIER_FACTOR: {
                    SymbolEntry entry = getSymbolEntry(currentCompilerState()->symbolTable, expression->factor->identifier);
                    if (entry.type == FLOAT_TYPE) {
                        return entry.value.floatData;
                    } else if (entry.type == INTEGER_TYPE) {
                        return (float)entry.value.integerData;
                    }
                    return 0.0f;
                }
                default:
                    return 0.0f;
            }
        case ADDITION:
            return _evaluateExpressionAsFloat(expression->leftExpression) + _evaluateExpressionAsFloat(expression->rightExpression);
        case SUBTRACTION:
            return _evaluateExpressionAsFloat(expression->leftExpression) - _evaluateExpressionAsFloat(expression->rightExpression);
        case MULTIPLICATION:
            return _evaluateExpressionAsFloat(expression->leftExpression) * _evaluateExpressionAsFloat(expression->rightExpression);
        case DIVISION: {
            float right = _evaluateExpressionAsFloat(expression->rightExpression);
            if (right != 0.0f) {
                return _evaluateExpressionAsFloat(expression->leftExpression) / right;
            }
            return 0.0f;
        }
        case GET_X: {
            VectorData vec = _evaluateExpressionAsVector(expression->expression);
            return vec.x;
        }
        case GET_Y: {
            VectorData vec = _evaluateExpressionAsVector(expression->expression);
            return vec.y;
        }
        case FUNCTION_EXPRESSION:
            if (strcmp(expression->functionIdentifier, "sqrt") == 0) {
                if (expression->functionArguments && expression->functionArguments->expressions) {
                    float arg = _evaluateExpressionAsFloat(expression->functionArguments->expressions->expression);
                    return sqrtf(arg);
                }
            }
            return 0.0f;
        default:
            return 0.0f;
    }
}

/**
 * Evaluates an expression and returns its integer value
 */
static int _evaluateExpressionAsInt(Expression * expression) {
    return (int)_evaluateExpressionAsFloat(expression);
}

/**
 * Evaluates an expression and returns its vector value
 */
static VectorData _evaluateExpressionAsVector(Expression * expression) {
    VectorData result = {0.0f, 0.0f};
    
    if (!expression) return result;
    
    switch (expression->type) {
        case FACTOR:
            if (expression->factor->type == VECTOR_FACTOR) {
                result.x = _evaluateExpressionAsFloat(expression->factor->vector->x);
                result.y = _evaluateExpressionAsFloat(expression->factor->vector->y);
            } else if (expression->factor->type == IDENTIFIER_FACTOR) {
                SymbolEntry entry = getSymbolEntry(currentCompilerState()->symbolTable, expression->factor->identifier);
                if (entry.type == VECTOR_TYPE) {
                    result = entry.value.vectorData;
                }
            }
            break;
        case ADDITION:
            {
                VectorData left = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData right = _evaluateExpressionAsVector(expression->rightExpression);
                result.x = left.x + right.x;
                result.y = left.y + right.y;
            }
            break;
        case SUBTRACTION:
            {
                VectorData left = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData right = _evaluateExpressionAsVector(expression->rightExpression);
                result.x = left.x - right.x;
                result.y = left.y - right.y;
            }
            break;
        default:
            break;
    }
    
    return result;
}

/**
 * Generates a circle element
 */
static void _generateCircle(FILE* outputFile, ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    // First argument should be position (vector)
    VectorData position = _evaluateExpressionAsVector(arguments->expressions->expression);
    
    // Second argument should be radius (float)
    float radius = 50.0f; // default
    if (arguments->expressions->next) {
        radius = _evaluateExpressionAsFloat(arguments->expressions->next->expression);
    }
    
    // Convert to SVG coordinates (center the drawing)
    float svgX = _centerX + position.x;
    float svgY = _centerY - position.y; // Flip Y axis
    
    char* fillColor = _colorToHex(_svgContext.fillColor);
    char* strokeColor = _colorToHex(_svgContext.strokeColor);
    
    fprintf(outputFile, "  <circle cx=\"%.2f\" cy=\"%.2f\" r=\"%.2f\" fill=\"%s\" stroke=\"%s\" stroke-width=\"%d\" class=\"%s-layer\"/>\n",
            svgX, svgY, radius, fillColor, strokeColor, _svgContext.strokeWidth,
            _svgContext.layer == 1 ? "front" : "back");
    
    free(fillColor);
    free(strokeColor);
}

/**
 * Generates a curve (Bezier path)
 */
static void _generateCurve(FILE* outputFile, ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    Expressions* expr = arguments->expressions;
    if (!expr || !expr->next || !expr->next->next || !expr->next->next->next) return;
    
    VectorData p1 = _evaluateExpressionAsVector(expr->expression);
    VectorData cp1 = _evaluateExpressionAsVector(expr->next->expression);
    VectorData cp2 = _evaluateExpressionAsVector(expr->next->next->expression);
    VectorData p2 = _evaluateExpressionAsVector(expr->next->next->next->expression);
    
    // Convert to SVG coordinates
    float x1 = _centerX + p1.x;
    float y1 = _centerY - p1.y;
    float cx1 = _centerX + cp1.x;
    float cy1 = _centerY - cp1.y;
    float cx2 = _centerX + cp2.x;
    float cy2 = _centerY - cp2.y;
    float x2 = _centerX + p2.x;
    float y2 = _centerY - p2.y;
    
    char* fillColor = _colorToHex(_svgContext.fillColor);
    char* strokeColor = _colorToHex(_svgContext.strokeColor);
    
    fprintf(outputFile, "  <path d=\"M %.2f %.2f C %.2f %.2f %.2f %.2f %.2f %.2f\" fill=\"%s\" stroke=\"%s\" stroke-width=\"%d\" class=\"%s-layer\"/>\n",
            x1, y1, cx1, cy1, cx2, cy2, x2, y2, fillColor, strokeColor, _svgContext.strokeWidth,
            _svgContext.layer == 1 ? "front" : "back");
    
    free(fillColor);
    free(strokeColor);
}

/**
 * Sets the stroke color
 */
static void _generateStroke(ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    int color = _evaluateExpressionAsInt(arguments->expressions->expression);
    _svgContext.strokeColor = color;
}

/**
 * Sets the fill color
 */
static void _generateFill(ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    int color = _evaluateExpressionAsInt(arguments->expressions->expression);
    _svgContext.fillColor = color;
}

/**
 * Sets the layer (z-order)
 */
static void _generateLayer(ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    int layer = _evaluateExpressionAsInt(arguments->expressions->expression);
    _svgContext.layer = layer;
}

/**
 * Generates log output (as SVG comment)
 */
static void _generateLog(FILE* outputFile, StringPartList * stringParts) {
    fprintf(outputFile, "  <!-- Log: ");
    _generateStringOutput(outputFile, stringParts);
    fprintf(outputFile, " -->\n");
}

/**
 * Generates import (as SVG comment)
 */
static void _generateImport(FILE* outputFile, StringPartList * importPath) {
    fprintf(outputFile, "  <!-- Import: ");
    _generateStringOutput(outputFile, importPath);
    fprintf(outputFile, " -->\n");
}

/**
 * Outputs interpolated string content
 */
static void _generateStringOutput(FILE* outputFile, StringPartList * stringParts) {
    if (!stringParts) return;
    
    _generateStringOutput(outputFile, stringParts->next);
    
    if (stringParts->stringPart) {
        if (stringParts->stringPart->type == STRING_SEGMENT) {
            fprintf(outputFile, "%s", stringParts->stringPart->string);
        } else if (stringParts->stringPart->type == IDENTIFIER_SEGMENT) {
            SymbolEntry entry = getSymbolEntry(currentCompilerState()->symbolTable, stringParts->stringPart->identifier);
            switch (entry.type) {
                case INTEGER_TYPE:
                    fprintf(outputFile, "%d", entry.value.integerData);
                    break;
                case FLOAT_TYPE:
                    fprintf(outputFile, "%.2f", entry.value.floatData);
                    break;
                case VECTOR_TYPE:
                    fprintf(outputFile, "(%.2f, %.2f)", entry.value.vectorData.x, entry.value.vectorData.y);
                    break;
                default:
                    fprintf(outputFile, "%s", stringParts->stringPart->identifier);
                    break;
            }
        }
    }
}

/**
 * Generates function calls
 */
static void _generateFunctionCall(FILE* outputFile, char * functionName, ExpressionList * arguments) {
    if (strcmp(functionName, "circle") == 0) {
        _generateCircle(outputFile, arguments);
    } else if (strcmp(functionName, "curve") == 0) {
        _generateCurve(outputFile, arguments);
    } else if (strcmp(functionName, "stroke") == 0) {
        _generateStroke(arguments);
    } else if (strcmp(functionName, "fill") == 0) {
        _generateFill(arguments);
    } else if (strcmp(functionName, "layer") == 0) {
        _generateLayer(arguments);
    }
}

/**
 * Generates a sentence
 */
static void _generateSentence(FILE* outputFile, Sentence * sentence) {
    if (!sentence) return;
    
    switch (sentence->type) {
        case FUNCTION_SENTENCE:
            _generateFunctionCall(outputFile, sentence->functionIdentifier, sentence->functionArguments);
            break;
        case LOG_SENTENCE:
            _generateLog(outputFile, sentence->logString);
            break;
        case IMPORT_SENTENCE:
            _generateImport(outputFile, sentence->importPath);
            break;
        case ASSIGN_SENTENCE:
        case ASSIGN_ARRAY_SENTENCE:
        case ASSIGN_ARRAY_ELEMENT_SENTENCE:
            // These don't generate visual output, but update the symbol table
            break;
        case IF_SENTENCE:
            // For simplicity, always execute the IF block in SVG generation
            // In a full implementation, you'd evaluate the boolean condition
            if (sentence->ifBlock) {
                _generateSentences(outputFile, sentence->ifBlock->sentences);
            }
            break;
        case IF_ELSE_SENTENCE:
            // For simplicity, always execute the IF block in SVG generation
            if (sentence->leftIfElseBlock) {
                _generateSentences(outputFile, sentence->leftIfElseBlock->sentences);
            }
            break;
        case FOR_SENTENCE:
            // For simplicity, skip FOR loops in SVG generation for now
            // In a full implementation, you'd iterate through the array
            if (sentence->forBlock) {
                _generateSentences(outputFile, sentence->forBlock->sentences);
            }
            break;
    }
}

/**
 * Generates sentences recursively
 */
static void _generateSentences(FILE* outputFile, Sentences * sentences) {
    if (!sentences) return;
    
    _generateSentences(outputFile, sentences->sentences);
    _generateSentence(outputFile, sentences->sentence);
}

/**
 * Generates the entire program
 */
static void _generateProgram(FILE* outputFile, Program * program) {
    if (!program) return;
    
    _generateSentences(outputFile, program->sentences);
}

/** PUBLIC FUNCTIONS */

void generate(CompilerState * compilerState) {
    logDebugging(_logger, "Generating SVG output...");
    
    FILE* outputFile = stdout; // Output to stdout
    
    _generateSVGHeader(outputFile);
    _generateProgram(outputFile, compilerState->abstractSyntaxtTree);
    _generateSVGFooter(outputFile);
    
    logDebugging(_logger, "SVG generation is done.");
}

void generateToFile(CompilerState * compilerState, const char * outputPath) {
    logDebugging(_logger, "Generating SVG output to file: %s", outputPath);
    
    FILE* outputFile = fopen(outputPath, "w");
    if (outputFile == NULL) {
        logError(_logger, "Failed to open output file: %s", outputPath);
        return;
    }
    
    _generateSVGHeader(outputFile);
    _generateProgram(outputFile, compilerState->abstractSyntaxtTree);
    _generateSVGFooter(outputFile);
    
    if (fclose(outputFile) != 0) {
        logError(_logger, "Failed to close output file: %s", outputPath);
    }
    
    logDebugging(_logger, "SVG generation to file is done.");
}
