#include "Generator.h"
#include "../../shared/CompilerState.h"
#include "../semantic-analysis/SymbolTable.h"
/* MODULE INTERNAL STATE */

static Logger * _logger = NULL;
static SVGContext _svgContext;
static int _svgWidth = 800;
static int _svgHeight = 600;
static int _centerX = 400;
static int _centerY = 300;

void initializeGeneratorModule() {
	_logger = createLogger("Generator");
	// Initialize default SVG context
	_svgContext.fillColor = 0x000000; // Black
	_svgContext.strokeColor = 0x000000; // Black
	_svgContext.strokeWidth = 1;
	_svgContext.layer = 0; // Back layer by default
}

void shutdownGeneratorModule() {
	if (_logger != NULL) {
		destroyLogger(_logger);
	}
}

/** PRIVATE FUNCTIONS */

static void _generateSVGHeader(FILE* outputFile);
static void _generateSVGFooter(FILE* outputFile);
static void _generateProgram(FILE* outputFile, Program * program);
static void _generateSentences(FILE* outputFile, Sentences * sentences);
static void _generateSentence(FILE* outputFile, Sentence * sentence);
// static void _generateExpression(Expression * expression);
// static void _generateFactor(Factor * factor);
static void _generateFunctionCall(FILE* outputFile, char * functionName, ExpressionList * arguments);
static void _generateCircle(FILE* outputFile, ExpressionList * arguments);
static void _generateCurve(FILE* outputFile, ExpressionList * arguments);
static void _generateStroke(ExpressionList * arguments);
static void _generateFill(ExpressionList * arguments);
static void _generateLayer(ExpressionList * arguments);
static void _generateLog(FILE* outputFile, StringPartList * stringParts);
static void _generateImport(FILE* outputFile, StringPartList * importPath);
static float _evaluateExpressionAsFloat(Expression * expression);
static int _evaluateExpressionAsInt(Expression * expression);
static VectorData _evaluateExpressionAsVector(Expression * expression);
static void _generateStringOutput(FILE* outputFile, StringPartList * stringParts);
static char* _colorToHex(int color);

/**
 * Converts a color integer to hex string format
 */
static char* _colorToHex(int color) {
    char* hexColor = malloc(8);
    sprintf(hexColor, "#%06X", color & 0xFFFFFF);
    return hexColor;
}

/**
 * Generates the SVG header with basic structure
 */
static void _generateSVGHeader(FILE* outputFile) {
    fprintf(outputFile, "<svg width=\"%d\" height=\"%d\" xmlns=\"http://www.w3.org/2000/svg\">\n", _svgWidth, _svgHeight);
    fprintf(outputFile, "  <defs>\n");
    fprintf(outputFile, "    <style>\n");
    fprintf(outputFile, "      .back-layer { z-index: 0; }\n");
    fprintf(outputFile, "      .front-layer { z-index: 1; }\n");
    fprintf(outputFile, "    </style>\n");
    fprintf(outputFile, "  </defs>\n");
    fprintf(outputFile, "  <!-- Generated by Dibujitos Compiler -->\n");
}

/**
 * Generates the SVG footer
 */
static void _generateSVGFooter(FILE* outputFile) {
    fprintf(outputFile, "</svg>\n");
}

/**
 * Evaluates an expression and returns its float value
 */
static float _evaluateExpressionAsFloat(Expression * expression) {
    if (!expression) return 0.0f;
    
    switch (expression->type) {
        case FACTOR:
            switch (expression->factor->type) {
                case INTEGER_FACTOR:
                    return (float)expression->factor->integerExpression;
                case DECIMAL_FACTOR:
                    return expression->factor->floatExpression;
                case IDENTIFIER_FACTOR: {
                    SymbolEntry entry = getSymbolEntry(currentCompilerState()->symbolTable, expression->factor->identifier);
                    if (entry.type == FLOAT_TYPE) {
                        return entry.value.floatData;
                    } else if (entry.type == INTEGER_TYPE) {
                        return (float)entry.value.integerData;
                    }
                    return 0.0f;
                }
                default:
                    return 0.0f;
            }
        case ADDITION:
            return _evaluateExpressionAsFloat(expression->leftExpression) + _evaluateExpressionAsFloat(expression->rightExpression);
        case SUBTRACTION:
            return _evaluateExpressionAsFloat(expression->leftExpression) - _evaluateExpressionAsFloat(expression->rightExpression);
        case MULTIPLICATION:
            return _evaluateExpressionAsFloat(expression->leftExpression) * _evaluateExpressionAsFloat(expression->rightExpression);
        case DIVISION: {
            float right = _evaluateExpressionAsFloat(expression->rightExpression);
            if (right != 0.0f) {
                return _evaluateExpressionAsFloat(expression->leftExpression) / right;
            }
            return 0.0f;
        }
        case GET_X: {
            VectorData vec = _evaluateExpressionAsVector(expression->expression);
            return vec.x;
        }
        case GET_Y: {
            VectorData vec = _evaluateExpressionAsVector(expression->expression);
            return vec.y;
        }
        case FUNCTION_EXPRESSION:
            if (strcmp(expression->functionIdentifier, "sqrt") == 0) {
                if (expression->functionArguments && expression->functionArguments->expressions) {
                    float arg = _evaluateExpressionAsFloat(expression->functionArguments->expressions->expression);
                    return sqrtf(arg);
                }
            }
            return 0.0f;
        default:
            return 0.0f;
    }
}

/**
 * Evaluates an expression and returns its integer value
 */
static int _evaluateExpressionAsInt(Expression * expression) {
    return (int)_evaluateExpressionAsFloat(expression);
}

/**
 * Evaluates an expression and returns its vector value
 */
static VectorData _evaluateExpressionAsVector(Expression * expression) {
    VectorData result = {0.0f, 0.0f};
    
    if (!expression) return result;
    
    switch (expression->type) {
        case FACTOR:
            if (expression->factor->type == VECTOR_FACTOR) {
                result.x = _evaluateExpressionAsFloat(expression->factor->vector->x);
                result.y = _evaluateExpressionAsFloat(expression->factor->vector->y);
            } else if (expression->factor->type == IDENTIFIER_FACTOR) {
                SymbolEntry entry = getSymbolEntry(currentCompilerState()->symbolTable, expression->factor->identifier);
                if (entry.type == VECTOR_TYPE) {
                    result = entry.value.vectorData;
                }
            }
            break;
        case ADDITION:
            {
                VectorData left = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData right = _evaluateExpressionAsVector(expression->rightExpression);
                result.x = left.x + right.x;
                result.y = left.y + right.y;
            }
            break;
        case SUBTRACTION:
            {
                VectorData left = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData right = _evaluateExpressionAsVector(expression->rightExpression);
                result.x = left.x - right.x;
                result.y = left.y - right.y;
            }
            break;
        case MULTIPLICATION:
            {
                VectorData left = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData right = _evaluateExpressionAsVector(expression->rightExpression);
                // Assuming multiplication is component-wise
                result.x = left.x * right.x;
                result.y = left.y * right.y;
            }
            break;
        default:
            break; // TODO ERROR    
    }
    
    return result;
}

/**
 * Generates a circle element
 */
static void _generateCircle(FILE* outputFile, ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    // First argument should be position (vector)
    VectorData position = _evaluateExpressionAsVector(arguments->expressions->expression);
    
    // Second argument should be radius (float)
    float radius = 50.0f; // default
    if (arguments->expressions->next) {
        radius = _evaluateExpressionAsFloat(arguments->expressions->next->expression);
    }
    
    // Convert to SVG coordinates (center the drawing)
    float svgX = _centerX + position.x;
    float svgY = _centerY - position.y; // Flip Y axis
    
    char* fillColor = _colorToHex(_svgContext.fillColor);
    char* strokeColor = _colorToHex(_svgContext.strokeColor);
    
    fprintf(outputFile, "  <circle cx=\"%.2f\" cy=\"%.2f\" r=\"%.2f\" fill=\"%s\" stroke=\"%s\" stroke-width=\"%d\" class=\"%s-layer\"/>\n",
            svgX, svgY, radius, fillColor, strokeColor, _svgContext.strokeWidth,
            _svgContext.layer == 1 ? "front" : "back");
    
    free(fillColor);
    free(strokeColor);
}

/**
 * Generates a curve (Bezier path)
 */
static void _generateCurve(FILE* outputFile, ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    Expressions* expr = arguments->expressions;
    if (!expr || !expr->next || !expr->next->next || !expr->next->next->next) return;
    
    VectorData p1 = _evaluateExpressionAsVector(expr->expression);
    VectorData cp1 = _evaluateExpressionAsVector(expr->next->expression);
    VectorData cp2 = _evaluateExpressionAsVector(expr->next->next->expression);
    VectorData p2 = _evaluateExpressionAsVector(expr->next->next->next->expression);
    
    // Convert to SVG coordinates
    float x1 = _centerX + p1.x;
    float y1 = _centerY - p1.y;
    float cx1 = _centerX + cp1.x;
    float cy1 = _centerY - cp1.y;
    float cx2 = _centerX + cp2.x;
    float cy2 = _centerY - cp2.y;
    float x2 = _centerX + p2.x;
    float y2 = _centerY - p2.y;
    
    char* fillColor = _colorToHex(_svgContext.fillColor);
    char* strokeColor = _colorToHex(_svgContext.strokeColor);
    
    fprintf(outputFile, "  <path d=\"M %.2f %.2f C %.2f %.2f %.2f %.2f %.2f %.2f\" fill=\"%s\" stroke=\"%s\" stroke-width=\"%d\" class=\"%s-layer\"/>\n",
            x1, y1, cx1, cy1, cx2, cy2, x2, y2, fillColor, strokeColor, _svgContext.strokeWidth,
            _svgContext.layer == 1 ? "front" : "back");
    
    free(fillColor);
    free(strokeColor);
}

/**
 * Sets the stroke color
 */
static void _generateStroke(ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    int color = _evaluateExpressionAsInt(arguments->expressions->expression);
    _svgContext.strokeColor = color;
}

/**
 * Sets the fill color
 */
static void _generateFill(ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    int color = _evaluateExpressionAsInt(arguments->expressions->expression);
    _svgContext.fillColor = color;
}

/**
 * Sets the layer (z-order)
 */
static void _generateLayer(ExpressionList * arguments) {
    if (!arguments || !arguments->expressions) return;
    
    int layer = _evaluateExpressionAsInt(arguments->expressions->expression);
    _svgContext.layer = layer;
}

/**
 * Generates log output (as SVG comment)
 */
static void _generateLog(FILE* outputFile, StringPartList * stringParts) {
    // fprintf(outputFile, "  <!-- Log: ");
    _generateStringOutput(outputFile, stringParts);
    // fprintf(outputFile, " -->\n");
}

/**
 * Generates import (as SVG comment)
 */
static void _generateImport(FILE* outputFile, StringPartList * importPath) {
    // fprintf(outputFile, "  <!-- Import: ");
    // _generateStringOutput(outputFile, importPath);
    // fprintf(outputFile, " -->\n");
}

/**
 * Outputs interpolated string content
 */
static void _generateStringOutput(FILE* outputFile, StringPartList * stringParts) {
    if (!stringParts) return;
    
    while(stringParts) {
        if (stringParts->stringPart) {
            if (stringParts->stringPart->type == STRING_SEGMENT) {
                const char *src = stringParts->stringPart->string;
                while (*src) {
                    if (src[0] == '\\' && src[1] == 'n') {
                        printf("\n");
                        src += 2;
                    } else {
                        putchar(*src);
                        src++;
                    }
                }
            } else if (stringParts->stringPart->type == IDENTIFIER_SEGMENT) {
                SymbolEntry entry = getSymbolEntry(currentCompilerState()->symbolTable, stringParts->stringPart->identifier);
                printSymbolValue(entry); 
            }
        }
        stringParts = stringParts->next;
    }
}

/**
 * Generates function calls
 */
static void _generateFunctionCall(FILE* outputFile, char * functionName, ExpressionList * arguments) {
    if (strcmp(functionName, "circle") == 0) {
        _generateCircle(outputFile, arguments);
    } else if (strcmp(functionName, "curve") == 0) {
        _generateCurve(outputFile, arguments);
    } else if (strcmp(functionName, "stroke") == 0) {
        _generateStroke(arguments);
    } else if (strcmp(functionName, "fill") == 0) {
        _generateFill(arguments);
    } else if (strcmp(functionName, "layer") == 0) {
        _generateLayer(arguments);
    }
}

void _generateAssignment(char* assignIdentifier, Expression *assignExpression) {
    if (!assignIdentifier || !assignExpression) return;
    
    SymbolEntry entry = getSymbolEntryWithScope(currentCompilerState()->symbolTable, assignIdentifier, currentCompilerState()->scopesStack);
    if (entry.type == NULL_TYPE) {
        logError(_logger, "Identifier '%s' not found in symbol table.", assignIdentifier);
        return;
    }
    
    switch (entry.type) {
        case INTEGER_TYPE:
            entry.value.integerData = _evaluateExpressionAsInt(assignExpression);
            break;
        case FLOAT_TYPE:
            entry.value.floatData = _evaluateExpressionAsFloat(assignExpression);
            break;
        case VECTOR_TYPE:
            entry.value.vectorData = _evaluateExpressionAsVector(assignExpression);
            break;
        default:
            logError(_logger, "Cannot assign to identifier '%s' of type %s.", assignIdentifier, symbolTypeToString(entry.type));
            return;
    }
    
    updateSymbol(currentCompilerState()->symbolTable, entry);
}

int _evaluateExpressionAsBool(BoolExpression *expression) {
    if (!expression) return false; 

    switch (expression->type) {
        case GREATER_OR_EQUAL: {
            SymbolType leftType = typeOfExpression(expression->leftExpression);
            if (leftType == INTEGER_TYPE) {
                return _evaluateExpressionAsInt(expression->leftExpression) >= _evaluateExpressionAsInt(expression->rightExpression);
            } else if (leftType == FLOAT_TYPE) {
                return _evaluateExpressionAsFloat(expression->leftExpression) >= _evaluateExpressionAsFloat(expression->rightExpression);
            } else if (leftType == VECTOR_TYPE) {
                VectorData v1 = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData v2 = _evaluateExpressionAsVector(expression->rightExpression);
                return (v1.x >= v2.x && v1.y >= v2.y);
            }
            return false;
        }
        case LESS_OR_EQUAL: {
            SymbolType leftType = typeOfExpression(expression->leftExpression);
            if (leftType == INTEGER_TYPE) {
                return _evaluateExpressionAsInt(expression->leftExpression) <= _evaluateExpressionAsInt(expression->rightExpression);
            } else if (leftType == FLOAT_TYPE) {
                return _evaluateExpressionAsFloat(expression->leftExpression) <= _evaluateExpressionAsFloat(expression->rightExpression);
            } else if (leftType == VECTOR_TYPE) {
                VectorData v1 = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData v2 = _evaluateExpressionAsVector(expression->rightExpression);
                return (v1.x <= v2.x && v1.y <= v2.y);
            }
            return false;
        }
        case GREATER_THAN: {
            SymbolType leftType = typeOfExpression(expression->leftExpression);
            if (leftType == INTEGER_TYPE) {
                return _evaluateExpressionAsInt(expression->leftExpression) > _evaluateExpressionAsInt(expression->rightExpression);
            } else if (leftType == FLOAT_TYPE) {
                return _evaluateExpressionAsFloat(expression->leftExpression) > _evaluateExpressionAsFloat(expression->rightExpression);
            } else if (leftType == VECTOR_TYPE) {
                VectorData v1 = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData v2 = _evaluateExpressionAsVector(expression->rightExpression);
                return (v1.x > v2.x && v1.y > v2.y);
            }
            return false;
        }
        case LESS_THAN: {
            SymbolType leftType = typeOfExpression(expression->leftExpression);
            if (leftType == INTEGER_TYPE) {
                return _evaluateExpressionAsInt(expression->leftExpression) < _evaluateExpressionAsInt(expression->rightExpression);
            } else if (leftType == FLOAT_TYPE) {
                return _evaluateExpressionAsFloat(expression->leftExpression) < _evaluateExpressionAsFloat(expression->rightExpression);
            } else if (leftType == VECTOR_TYPE) {
                VectorData v1 = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData v2 = _evaluateExpressionAsVector(expression->rightExpression);
                return (v1.x < v2.x && v1.y < v2.y);
            }
            return false;
        }
        case EQUAL_TO: {
            SymbolType leftType = typeOfExpression(expression->leftExpression);
            if (leftType == INTEGER_TYPE) {
                return _evaluateExpressionAsInt(expression->leftExpression) == _evaluateExpressionAsInt(expression->rightExpression);
            } else if (leftType == FLOAT_TYPE) {
                return _evaluateExpressionAsFloat(expression->leftExpression) == _evaluateExpressionAsFloat(expression->rightExpression);
            } else if (leftType == VECTOR_TYPE) {
                VectorData v1 = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData v2 = _evaluateExpressionAsVector(expression->rightExpression);
                return (v1.x == v2.x && v1.y == v2.y);
            }
            return false;
        }
        case NOT_EQUAL: {
            SymbolType leftType = typeOfExpression(expression->leftExpression);
            if (leftType == INTEGER_TYPE) {
                return _evaluateExpressionAsInt(expression->leftExpression) != _evaluateExpressionAsInt(expression->rightExpression);
            } else if (leftType == FLOAT_TYPE) {
                return _evaluateExpressionAsFloat(expression->leftExpression) != _evaluateExpressionAsFloat(expression->rightExpression);
            } else if (leftType == VECTOR_TYPE) {
                VectorData v1 = _evaluateExpressionAsVector(expression->leftExpression);
                VectorData v2 = _evaluateExpressionAsVector(expression->rightExpression);
                return (v1.x != v2.x || v1.y != v2.y);
            }
            return false;
        }
        case AND_TYPE:
            return _evaluateExpressionAsBool(expression->leftBoolExpression) && _evaluateExpressionAsBool(expression->rightBoolExpression);
        case OR_TYPE:
            return _evaluateExpressionAsBool(expression->leftBoolExpression) || _evaluateExpressionAsBool(expression->rightBoolExpression);
        case NOT_TYPE:
            return !_evaluateExpressionAsBool(expression->boolExpression);
        case BOOL_FACTOR:
            return _evaluateExpressionAsBool(expression->boolFactor->boolExpression);
        default:
            break;
        }
        return false;
}

void _generateArrayAssignment(char *arrayIdentifier, Array *array) { // TODO
    if (!arrayIdentifier || !array) return;
    SymbolEntry entry = getSymbolEntryWithScope(currentCompilerState()->symbolTable, arrayIdentifier, currentCompilerState()->scopesStack);
    if (entry.type == NULL_TYPE) {
        logError(_logger, "Array identifier '%s' not found in symbol table.", arrayIdentifier);
        return;
    }
    if (entry.type != ARRAY_TYPE) {
        logError(_logger, "Identifier '%s' is not an array.", arrayIdentifier);
        return;
    }

    switch (array->type)
    {
    case IDENTIFIER_ARRAY:
        // TODO
        break;
    case INTERVAL_ARRAY:
        // TODO
        break;
    case BASIC_ARRAY:
        if (!array->expressionList) {
            logError(_logger, "Array '%s' has no elements.", arrayIdentifier);
            return;
        }
        entry.value.arrayData.dataType = typeOfExpression(array->expressionList->expressions->expression);
        entry.value.arrayData.elements = malloc(sizeof(BasicType) * entry.value.arrayData.size);
        int i = 0;
        Expressions *current = array->expressionList->expressions;
        while (current) {
            switch (typeOfExpression(current->expression))
            {
            case FLOAT_TYPE:
                entry.value.arrayData.elements[i].type = FLOAT_TYPE;
                entry.value.arrayData.elements[i].value.floatData = _evaluateExpressionAsFloat(current->expression);
                break;
            case INTEGER_TYPE:
                entry.value.arrayData.elements[i].type = INTEGER_TYPE;
                entry.value.arrayData.elements[i].value.integerData = _evaluateExpressionAsInt(current->expression);
                break;
            case VECTOR_TYPE:
                entry.value.arrayData.elements[i].type = VECTOR_TYPE;
                entry.value.arrayData.elements[i].value.vectorData = _evaluateExpressionAsVector(current->expression);
                break;
            default:
                break; // WTF
            }
            current = current->next;
            i++;
        }
        entry.value.arrayData.dataType = BASIC_ARRAY;
        entry.value.arrayData.size = i;

        break;
    default:
        break;
    }

    updateSymbol(currentCompilerState()->symbolTable, entry);
}

void _generateForLoop(FILE* outputFile, char *iterator, Array *array, Sentences *block) {
    if (!iterator || !array || !block) return;    

    SymbolEntry iteratorEntry = getSymbolEntry(currentCompilerState()->symbolTable, iterator);
    if (iteratorEntry.type == NULL_TYPE) {
        logError(_logger, "Loop variable '%s' not found in symbol table.", iterator);
        return;
    }

    switch (array->type) {
    case IDENTIFIER_ARRAY: {
        SymbolEntry arrayEntry = getSymbolEntryWithScope(currentCompilerState()->symbolTable, array->identifier, currentCompilerState()->scopesStack);
        if (arrayEntry.type != ARRAY_TYPE) {
            logError(_logger, "Identifier '%s' is not an array.", array->identifier);
            return;
        }
        for (int i = 0; i < arrayEntry.value.arrayData.size; i++) {
            switch (arrayEntry.value.arrayData.elements[i].type)
            {
            case INTEGER_TYPE:
                iteratorEntry.value.integerData = arrayEntry.value.arrayData.elements[i].value.integerData;
                break;
            case FLOAT_TYPE:
                iteratorEntry.value.floatData = arrayEntry.value.arrayData.elements[i].value.floatData;
                break;
            case VECTOR_TYPE:
                iteratorEntry.value.vectorData = arrayEntry.value.arrayData.elements[i].value.vectorData;
                break;
            default:
                break;
            }
            updateSymbol(currentCompilerState()->symbolTable, iteratorEntry);
            _generateSentences(outputFile, block);
        }
        break;
    }
    case BASIC_ARRAY: {
        Expressions *current = array->expressionList->expressions;
        while (current) {
            switch (typeOfExpression(current->expression))
            {
            case INTEGER_TYPE:
                iteratorEntry.value.integerData = _evaluateExpressionAsInt(current->expression);
                break;
            case FLOAT_TYPE:
                iteratorEntry.value.floatData = _evaluateExpressionAsFloat(current->expression);
                break;
            case VECTOR_TYPE:
                iteratorEntry.value.vectorData = _evaluateExpressionAsVector(current->expression);
                break;
            default:
                break;
            }
            updateSymbol(currentCompilerState()->symbolTable, iteratorEntry);
            _generateSentences(outputFile, block);
            current = current->next;
        }
        break;
    }
    case INTERVAL_ARRAY: {
        int start = _evaluateExpressionAsInt(array->leftExpression);
        int end = _evaluateExpressionAsInt(array->rightExpression);
        while(start <= end) {
            iteratorEntry.value.integerData = start;
            updateSymbol(currentCompilerState()->symbolTable, iteratorEntry);
            _generateSentences(outputFile, block);
            start++;
        }
        break;
    }
    
    default:
        break;
    }
}

void _generateArrayElementAssignment(char *arrayIdentifier, Expression *arrayIndexExpression, Expression *arrayElementExpression) {
    if (!arrayIdentifier || !arrayIndexExpression || !arrayElementExpression) return;
    
    SymbolEntry entry = getSymbolEntryWithScope(currentCompilerState()->symbolTable, arrayIdentifier, currentCompilerState()->scopesStack);
    if (entry.type == NULL_TYPE) {
        logError(_logger, "Array identifier '%s' not found in symbol table.", arrayIdentifier);
        return;
    }
    if (entry.type != ARRAY_TYPE) {
        logError(_logger, "Identifier '%s' is not an array.", arrayIdentifier);
        return;
    }
    
    int index = _evaluateExpressionAsInt(arrayIndexExpression);
    if (index < 0 || index >= entry.value.arrayData.size) {
        logError(_logger, "Index %d out of bounds for array '%s'.", index, arrayIdentifier);
        return; // TODO error
    }
    
    switch (entry.value.arrayData.elements[index].type) {
    case INTEGER_TYPE:
        entry.value.arrayData.elements[index].value.integerData = _evaluateExpressionAsInt(arrayElementExpression);
        break;
    case FLOAT_TYPE:
        entry.value.arrayData.elements[index].value.floatData = _evaluateExpressionAsFloat(arrayElementExpression);
        break;
    case VECTOR_TYPE:
        entry.value.arrayData.elements[index].value.vectorData = _evaluateExpressionAsVector(arrayElementExpression);
        break;
    default:
        logError(_logger, "Cannot assign to array '%s' of type %s.", arrayIdentifier, symbolTypeToString(entry.type));
        return;
    }
        
    updateSymbol(currentCompilerState()->symbolTable, entry);
}
/**
 * Generates a sentence
 */
static void _generateSentence(FILE* outputFile, Sentence * sentence) {
    if (!sentence) return;
    
    switch (sentence->type) {
        case FUNCTION_SENTENCE:
            _generateFunctionCall(outputFile, sentence->functionIdentifier, sentence->functionArguments);
            break;
        case LOG_SENTENCE:
            _generateLog(outputFile, sentence->logString);
            break;
        case IMPORT_SENTENCE:
            _generateImport(outputFile, sentence->importPath);
            break;
        case ASSIGN_SENTENCE:
            _generateAssignment(sentence->assignIdentifier, sentence->assignExpression);
            break;
        case ASSIGN_ARRAY_SENTENCE:
            _generateArrayAssignment(sentence->assignArrayIdentifier, sentence->assignArray);
            break;
        case ASSIGN_ARRAY_ELEMENT_SENTENCE:
            _generateArrayElementAssignment(sentence->assignArrayElemIdentifier, sentence->assignArrayIndexExpression, sentence->assignArrayElementExpression);
            break;
        case IF_SENTENCE:
            if (_evaluateExpressionAsBool(sentence->ifBoolExpression)) {
                _generateSentences(outputFile, sentence->ifBlock->sentences);
            }
            break;
        case IF_ELSE_SENTENCE:
            if (_evaluateExpressionAsBool(sentence->ifBoolExpression)) {
                _generateSentences(outputFile, sentence->leftIfElseBlock->sentences);
            }
            else {
                _generateSentences(outputFile, sentence->rightIfElseBlock->sentences);
            }
            break;
        case FOR_SENTENCE:
            _generateForLoop(outputFile, sentence->forIdentifier, sentence->forArray, sentence->forBlock->sentences);
            break;
    }
}

/**
 * Generates sentences recursively
 */
static void _generateSentences(FILE* outputFile, Sentences * sentences) {
    if (!sentences) return;
    
    _generateSentences(outputFile, sentences->sentences);
    _generateSentence(outputFile, sentences->sentence);
}

/**
 * Generates the entire program
 */
static void _generateProgram(FILE* outputFile, Program * program) {
    if (!program) return;
    
    _generateSentences(outputFile, program->sentences);
}

/** PUBLIC FUNCTIONS */

void generate(CompilerState * compilerState) {
    logDebugging(_logger, "Generating SVG output...");
    
    FILE* outputFile = stdout; // Output to stdout
    
    _generateSVGHeader(outputFile);
    _generateProgram(outputFile, compilerState->abstractSyntaxtTree);
    _generateSVGFooter(outputFile);
    
    logDebugging(_logger, "SVG generation is done.");
}

void generateToFile(CompilerState * compilerState, const char * outputPath) {
    logDebugging(_logger, "Generating SVG output to file: %s", outputPath);
    
    FILE* outputFile = fopen(outputPath, "w");
    if (outputFile == NULL) {
        logError(_logger, "Failed to open output file: %s", outputPath);
        return;
    }
    
    _generateSVGHeader(outputFile);
    _generateProgram(outputFile, compilerState->abstractSyntaxtTree);
    _generateSVGFooter(outputFile);
    
    if (fclose(outputFile) != 0) {
        logError(_logger, "Failed to close output file: %s", outputPath);
    }
    
    logDebugging(_logger, "SVG generation to file is done.");
}
